-- 깃이나 버전에서 같이 관리가 가능하기에 따로 sql 폴더 및 .sql 파일작성 --

drop table if exists member CASCADE;

create table member
(
  id  bigint generated by default as identity,
  -- bigint는 Long이다.--
  -- generated by default as identity은 값을 설정하지 않고 (null)들어오면 db가 자동으로 채움-->
  name varchar(255),
  primary key(id)
);

select *from member;

insert into member(name) values('spring‘);